name: release

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      target_release_tag:
        description: Git tag to attach build artifacts to
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle
            ./libs
          key: ${{ runner.os }}-gradle-common
          restore-keys: |
            ${{ runner.os }}-gradle-common

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build fabricWrapper subproject
        run: ./gradlew :fabricWrapper:build --stacktrace

      - name: Delete sources jar
        run: |
          find fabricWrapper/build/libs/ -name "*-sources.jar" -exec rm {} \;

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: fabricWrapper/build/libs/*
          token: ${{ secrets.GITHUB_TOKEN }}
